### ISSUE TITLE
dateWeekEnd error

### ISSUE THREAD

**Issue by Koshub** [belkevich/nsdate-calendar#6]
myDate.dateWeekEnd returns date less then date of called object myDate

**Comment by belkevich** [comment]
please, provide steps to reproduce

**Comment by Koshub** [comment]
Sorry, I thought it was easy to reproduce .... but it is not


```swift
let now = NSDate(year: 2015, month: 1, day: 17, hour: 9, minute: 33, second: 35)
println("\(now.dateWeekStart()) \(now) \(now.dateWeekEnd()) ")
```
2015-01-10 22:00:00 +0000 2015-01-17 07:33:35 +0000 2015-01-16 22:00:00 +0000

**Comment by belkevich** [comment]
Ok, I'll check it

**Comment by belkevich** [comment]
I've checked this issue. Actually it's normal behaviour)) 
Your local calendar time is UTC+2, right?
2015-01-17 07:33:35 - is Saturday and it's last day of the week
2015-01-10 22:00:00 - is 00 AM of Sunday 01-11 (UTC+2!) - everything ok
2015-01-16 22:00:00 - is 00 AM of Saturday 01-17 (UTC+2!) - so it's ok either))

weekEnd/Start is good feature to develop some kind of calendar app. That's why weekEnd ignores 'time'-component.
If you have any suggestions please write it here, otherwise I'll close issue

**Comment by Koshub** [comment]
No, I think there should be test which should check that source date should be between  dateWeekStart and dateWeekEnd. When this test receives date NSDate(year: 2015, month: 1, day: 17, hour: 9, minute: 33, second: 35) it should pass.

**Comment by belkevich** [comment]
ok, so what is the right 'dateWeekEnd' for '2015-01-17 09:33:35'?

**Comment by Koshub** [comment]
Sorry, don't have time for this repo

**Comment by belkevich** [comment]
It's ok. Feel free to reopen this issue when you have more time
